### ISSUE TITLE
scheduling not working after gMSA deployed

### ISSUE THREAD

**Issue by aaronsssya** [aws-samples/amazon-eks-gmsa#1]
I tried deployed gMSA on my EKS with my owned AD. It is running as the following.

```text
kubectl  get pods --all-namespaces
NAMESPACE      NAME                                       READY   STATUS    RESTARTS   AGE
gmsa-webhook   webhook-svc-5fb6dc7775-qdw8r               1/1     Running   0          13m
kube-system    aws-node-km55k                             1/1     Running   0          22h
kube-system    coredns-5b9879fcff-9fnks                   1/1     Running   0          119m
kube-system    coredns-5b9879fcff-rlwlz                   1/1     Running   0          119m
kube-system    kube-proxy-gtdwd                           1/1     Running   0          22h
kube-system    vpc-admission-webhook-6d4f7dc54f-9zs7c     1/1     Running   0          22h
kube-system    vpc-resource-controller-5ddd7b84dd-55d6j   1/1     Running   0          22h
```

However, The scheduling won't work. It looks like hang.

```text
kubectl get deployment
NAME          READY   UP-TO-DATE   AVAILABLE   AGE
aspnet        0/1     0            0           4h53m
```

In Additional, vpc-admission-webhook.kube-system will disappear
lost vpc-admission-webhook.kube-system
```text
kubectl get certificatesigningrequest
NAME                       AGE   REQUESTOR                                                 CONDITION
csr-f22tm                  66m   system:node:ip-10-131-25-114.us-west-2.compute.internal   Approved,Issued
csr-psw72                  41m   system:node:ip-10-131-25-153.us-west-2.compute.internal   Approved,Issued
webhook-svc.gmsa-webhook   11m   kubernetes-admin                                          Approved,Issued
```
Should be like this
```text
kubectl get certificatesigningrequest
NAME                                AGE   REQUESTOR                                                 CONDITION
csr-f22tm                           74m   system:node:ip-10-131-25-114.us-west-2.compute.internal   Approved,Issued
csr-psw72                           49m   system:node:ip-10-131-25-153.us-west-2.compute.internal   Approved,Issued
vpc-admission-webhook.kube-system   4s    kubernetes-admin                                          Approved,Issued
webhook-svc.gmsa-webhook            20m   kubernetes-admin                                          Approved,Issued
```

**Comment by aaronsssya** [comment]
I performed kubectl describe replicaset, and then I got the following error

```text
Events:
  Type     Reason            Age                 From                   Message
  ----     ------            ----                ----                   -------
  Normal   SuccessfulCreate  26m                 replicaset-controller  Created pod: bastion-win-6f58689f5d-lnhb6
  Normal   SuccessfulCreate  25m                 replicaset-controller  Created pod: bastion-win-6f58689f5d-7lfgx
  Warning  FailedCreate      44s (x86 over 10h)  replicaset-controller  Error creating: Internal error occurred: failed calling webhook "admission-webhook.windows-gmsa.sigs.k8s.io": Post https://webhook-svc.gmsa-webhook.svc:443/mutate?timeout=30s: x509: certificate signed by unknown authority
```

**Comment by vsiddharth** [comment]
It looks like there could be multiple issues going on here. 
First, for EKS Windows pods to run successfully, the `vpc-admission-webhook` is critical. It injects the extended resource requirements for the pod. 

Could you please obtain relevant logs from the node where the `vpc-admission-webhook` was running and post them here? You could also check the logs of the `kube-apiserver` to determine what happened to the `vpc-admission-webhook`?

I have also never seen the certificate issue for the `gMSA webhook`.
Could you please post the relevant logs from that component too?

**Comment by aaronsssya** [comment]
Hi @vsiddharth,

I think the issue might cause by self sign. Ideally, EKS user cannot get cluster certificate key. Therefore, user cannot sigh authorized CA. I saw the same problem on KOPS. https://stackoverflow.com/questions/48172310/kubernetes-ca-file-when-deploying-via-kops. Good news for KOPS user. Kops user can download cluster ca from S3.

Regarding vpc-admission-webhook, its issue that caused by unauthorized gmsa-webhook as well. If I remove gmsa-webhook, everything running well. Therefore, I would like to know how to apply authorized ca gmsa-webhook from EKS.

Does EKS user can download cluster certificate key?

**Comment by somujay** [comment]
Looks like the secrets are messed up here. After customer tried the following steps, it worked. 

1) Create a new EKS cluster from your bastion host - linux EC2 instance
2) In that linux instance , install powershell core
3) clone steps at gmsa blog 
4) deploy  webhook
