### ISSUE TITLE
EKS Windows containers with group Managed Service Accounts (gMSA)

### ISSUE THREAD

**Issue by ravindravv** [aws-samples/amazon-eks-gmsa#5]
Hi All,
Hope you are doing well.
I am going through the Document to deploy EKS Windows Containers with gMSA. 
https://aws.amazon.com/blogs/containers/how-to-run-eks-windows-containers-with-group-managed-service-account-gmsa/
I have completed Part1, Part 2 and few are in part 3 successfully. 
I am getting failure when executing the below command.
$commandId = aws ssm send-command --document-name $credspecSSMdoc --targets "Key=InstanceIds,Values=$firstInstanceId" --parameters "gMSAAccount=$gMSAAccountName,AdditionalCredSpecAccounts=" --query "Command.CommandId" --outputtext

Error is

RequestedDateTime": "2020-08-13T18:54:43.925000+00:00",
"Status": "failed",
"StatusDetails": "failed",
"StandardOutputUrl": "",
"StandardErrorUrl": "",

The below error is from AWS Systems Manager ( Run command)

System.Management.Automation.ValidationMetadataException: The argument is null. Provide a valid value for the argument, and then try running the command again.
at System.Management.Automation.ValidateNotNullAttribute.Validate(Object arguments, EngineIntrinsics engineIntrinsics)
at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
Command execution failed.
Can you please provide your valuable inputs to resolve?

Could you please help me at the earliest?

Best Regards
Ravindra

**Comment by ravindravv** [comment]
Hi, Can anyone help on my above request?
Best Regards
Ravi

**Comment by lalwanin2020** [comment]
Hi Ravi

I need more information to help you resolve the error. 

1. What version of Windows AMI are you using?
2. Did you follow step 4 from [here](https://github.com/aws-samples/amazon-eks-gmsa/blob/master/eks-deployments/instance-domain-join.md) and did you encounter any error?
3. Did you encrypt your AD password as done in the Github implementation and can you check if the AD password parameter is present in the Parameter Store under Systems Manager? 

Regards
Naveen Lalwani

**Comment by ravindravv** [comment]
Hi Naveen,
Thank you for your reply.
The issue got resolve , Now, my Infrastructure is ready to deploy my applications. Here I am seeking help. It could be grateful if you can help me.
I have pushed my docker images to ECR. I want to deploy the application by using that image. 
Can you help me please?
Best Regards
Ravi

**Comment by lalwanin2020** [comment]
Hi Ravi

I am glad that your error was resolved. You need to pull the image from ECR on the windows instance which is domain joined and present in the cluster and use the image name and tag in your pod spec yaml file. You can refer the pulling an image from ECR guide [here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-pull-ecr-image.html) . 

You can refer the sample pod spec yaml files and dockerfile in the repository [here](https://github.com/aws-samples/amazon-eks-gmsa/blob/master/sample-applications/IIS-auth-application/windows-server-iis.yaml) for reference. 

I hope that you will be able to run your application now. 

Regards
Naveen Lalwani






.

**Comment by lalwanin2020** [comment]
The original problem is resolved. Hence, closing the issue.

**Comment by ravindravv** [comment]
Hi Naveen,
Thank you for sharing your valuable inputs. But i noticed the variable namespace: ${NAMESPACE}  is different in windows-server-iis.yaml. We didnot have any variable with namespace: ${NAMESPACE} but we had with $gMSAnamespace, Can you confirm please?

Best Regards
Ravi

**Comment by lalwanin2020** [comment]
Hi Ravi
The ${NAMESPACE} is the same as $gMSAnamespace. 
This is a variable we introduced in the yaml file to be replaced by the value of $gMSAnamespace using the Build-Container-Images.ps1 powershell script present in the same folder. 

Regards
Naveen Lalwani

**Comment by ravindravv** [comment]
Hi Naveen,
As you mentioned ,  You need to pull the image from ECR on the windows instance which is domain joined and present in the cluster and use the image name and tag in your pod spec yaml file. You can refer the pulling an image from ECR guide here .

1) It means, Do I need to pull the image on windows worker node which is domian joined and part of the cluster?


2) Can you revirew below one and conform? Please do the need.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ABC
  namespace: ${gmsaNAMESPACE}
spec:
  selector:
    matchLabels:
      app: ABC
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: ABC
        tier: backend
        track: stable
    spec:
      securityContext:
        windowsOptions:
          gmsaCredentialSpecName: ${CREDSPECRESOURCE}
      serviceAccountName: ${SERVICEACCOUNTNAME}
      containers:
      - name: ABC
        image: XXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/ABC:latest
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: Never
      nodeSelector:
        kubernetes.io/os: windows 



Best Regards
Ravi

**Comment by lalwanin2020** [comment]
Hi Ravi 

1. Yes, you need to pull the image on windows worker node which is domain joined and part of the cluster.
2. It looks fine, but replace the ${SERVICEACCOUNTNAME}, ${CREDSPECRESOURCE} & ${gmsaNAMESPACE} with the values that you have used for these variables during infrastructure setup. These variables are not automatically picked up. As I mentioned earlier, we use a powershell script to replace these values in the yaml file and then we create a new file with these variable replaced with actual values. Here, you can manually replace them for your yaml file. 

With the image, use the image name and tag, that you decide on while pulling the image on the node. Going through our code and application will be really helpful to understand on how we are running the application. This [application](https://github.com/aws-samples/amazon-eks-gmsa/tree/master/sample-applications/IIS-auth-application) is small and easy to understand, you can refer here to decide on your changes. 

Regards
Naveen Lalwani

**Comment by ravindravv** [comment]
HI Naveen,
1) I have pulled the image on windows worker node successfully
2) i have created yml file with the below details

apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc
  namespace: abceksgmsa
spec:
  selector:
    matchLabels:
      app: abc
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: abc
        tier: backend
        track: stable
    spec:
      securityContext:
        windowsOptions:
          gmsaCredentialSpecName: abceksgmsa
      serviceAccountName: gmsaserviceaccount
      containers:
      - name: bps
        image: XXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/ABC:latest
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: Never
      nodeSelector:
        kubernetes.io/os: windows
This yml file executed on my system with the below command 
PS C:\Users\rv50\Desktop\amazon-eks-gmsa-master\eks-deployments> kubectl apply -f abc.yml
deployment.apps/abc created
then i executed the below command
 kubectl get pods -n abceksgmsa
then i got 
No resources found in bpseksgmsa namespace.
-----------------
Do i need to excute the below command on worker node or my system? Please do the need.

kubectl apply -f abc.yml

Best Regards
Ravi

**Comment by ravindravv** [comment]
HI Naveen,

I have pulled the image on windows worker node successfully
i have created yml file with the below details
apiVersion: apps/v1
kind: Deployment
metadata:
name: abc
namespace: abceksgmsa
spec:
selector:
matchLabels:
app: abc
tier: backend
track: stable
replicas: 1
template:
metadata:
labels:
app: abc
tier: backend
track: stable
spec:
securityContext:
windowsOptions:
gmsaCredentialSpecName: abceksgmsa
serviceAccountName: gmsaserviceaccount
containers:
- name: abc
image: XXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/ABC:latest
ports:
- name: http
containerPort: 80
imagePullPolicy: Never
nodeSelector:
kubernetes.io/os: windows
This yml file executed on my system with the below command
PS C:\Users\rv50\Desktop\amazon-eks-gmsa-master\eks-deployments> kubectl apply -f abc.yml
deployment.apps/abc created
then i executed the below command
kubectl get pods -n abceksgmsa
then i got
No resources found in abceksgmsa namespace.

**Comment by lalwanin2020** [comment]
Hi Ravi 

Your pod spec file looks good to me. The problem could be with your image name or any of the variable names you have specified. Please check what is the name of the pulled image on your windows worker node.

Also, your setup seems incorrect to me as you should have our webhook svc pod running in the $gMSAnamespace so you should get at least one pod or resource. Kindly follow the repository to see if you missed any step.

A good way to check your setup would be to run our application from [here](https://github.com/aws-samples/amazon-eks-gmsa/tree/master/sample-applications/IIS-auth-application) and check if it's working or not. From there you can experiment with your application. You can also refer the troubleshooting section [here](https://github.com/aws-samples/amazon-eks-gmsa#5-troubleshooting).

Regards
Naveen Lalwani

**Comment by ravindravv** [comment]
kubectl  get pods --all-namespaces
NAMESPACE     NAME                                                READY   STATUS    RESTARTS   AGE
bpseksgmsa    webhook-svc-857b48b6c7-5mn8r                        1/1     Running   0          40m
default       windows-server-iis-7cff879775-wm8xb                 1/1     Running   0          165m
kube-system   aws-node-nwc8v                                      1/1     Running   0          6d16h
kube-system   coredns-75b44cb5b4-4jqhn                            1/1     Running   0          3h29m
kube-system   coredns-75b44cb5b4-bkw9d                            1/1     Running   0          39m
kube-system   kube-proxy-hsz6c                                    1/1     Running   0          6d16h
kube-system   vpc-admission-webhook-deployment-75ffd84dc9-tnzl7   1/1     Running   0          174m
kube-system   vpc-resource-controller-97c765b-lp4n2               1/1     Running   0          3h3m

**Comment by ravindravv** [comment]
> kubectl get certificatesigningrequest
NAME                     AGE   REQUESTOR          CONDITION
webhook-svc.bpseksgmsa   29m   kubernetes-admin   Approved,Issued

**Comment by ravindravv** [comment]
HI Naveen, 
I am looking for help to achieve . Can you help me please? 
Best Regards
Ravi

**Comment by ravindravv** [comment]
This is the yml file i am using
---------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bps
  namespace: bpseksgmsa
spec:
  selector:
    matchLabels:
      app: bps
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: bps
        tier: backend
        track: stable
    spec:
      securityContext:
        windowsOptions:
          gmsaCredentialSpecName: bpseksgmsa
      serviceAccountName: gmsaserviceaccount
      containers:
      - name: bps
        image: XXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/bps:latest
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: Never
      nodeSelector:
        kubernetes.io/os: windows

I am executing the command > kubectl apply -f bps.yml

PLease go through the above YML file and let me know

**Comment by ravindravv** [comment]
HI Naveen,
Can you please let me know your inputs on the above information?
Best Regards
Ravi

**Comment by lalwanin2020** [comment]
Hi Ravi

The yaml file looks fine. You can go ahead and run your application but will still urge you to verify your setup first using our application [here](https://github.com/aws-samples/amazon-eks-gmsa/tree/master/sample-applications/IIS-auth-application). 

Also, it is really difficult for us to have individual debugging sessions, so I would urge you to go through our [EKS gMSA blog](https://aws.amazon.com/blogs/containers/how-to-run-eks-windows-containers-with-group-managed-service-account-gmsa/) and Github [repository](https://github.com/aws-samples/amazon-eks-gmsa) and [troubleshooting guide](https://github.com/aws-samples/amazon-eks-gmsa#5-troubleshooting) for solving nitpicking errors. You can also refer the Kubernetes official documentation [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/) for more information. 

Regards
Naveen Lalwani
